routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/', function () {
    return view('auth/login');
});
Auth::routes();

Route::get('/home', 'PostController@index')->name('home');
Route::resource('/post', 'PostController');
Route::resource('/profile', 'ProfileController');
Route::post('/post/{post}/comment', 'CommentPostController@store')->name('post.comment.store');

Route::get('/commen/like/{id}', [
    'uses' => 'LikeCommentPostController@like',
    'as' => 'comment.like'
]);

Route::get('/post/like/{id}', [
    'uses' => 'LikePostController@like',
    'as' => 'post.like'
]);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['post_content', 'post_image', 'user_id'];

    // relationship one to many (user -> post)
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    // relationship one to many (user -> commentPost)
    public function commentPost()
    {
        return $this->hasMany(CommentPost::class);
    }
    // relationship one to many (post -> likePost)
    public function liketPost()
    {
        return $this->hasMany(LikePost::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Profile;
use App\Following;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data_post = Post::orderByRaw('created_at DESC')->get();

        // rubah ke popular post 
        $latest_post = Post::orderByRaw('created_at DESC')->paginate(5);

        // create profile with null edentity 
        $id_profile = Profile::where('user_id', Auth::id())->first();
        if (empty($id_profile)) {
            $profile = new Profile();
            $profile->profile_image     = 'avatar.png';
            $profile->user_id     = Auth::id();
            $profile->save();
        }

        return view('post.index', compact('data_post', 'latest_post'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post();
        $post->post_content   = $request->input('post_content');
        $image                   = $request->file('postImageName');
        $imageName   = 'pImage-' . $image->getClientOriginalName();
        $image->move('postImage/', $imageName);
        $post->post_image  = $imageName;
        $post->user_id     = Auth::id();
        $post->save();
        return back()->with("success", "Posted Successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data_post = Post::find($id);
        // rubah ke popular post 
        $latest_post = Post::orderByRaw('created_at DESC')->paginate(5);
        return view('post.show', compact('data_post', 'latest_post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data_post = Post::find($id);
        return view('post.edit', compact('data_post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findorfail($id);

        $data_post = [
            'post_content' => $request->post_content,
        ];

        $post->update($data_post);

        return redirect()->route('post.index')->with('success', 'Edited Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();
        return redirect()->route('post.index')->with('success', 'Removed Successfully');
    }
}

resources/views/post/edit.blade.php
@extends('layouts.master')
@section('content')
<section class="content">
  <div class="container">
    <div class="row">
      <!-- Edit Post -->
      <div class="box">
        <div class="box-header border-transparent">
          <div class="user-block">
            <img class="img-circle img-bordered-sm" src="{{URL::to('/')}}/profileImage/{{Auth::user()->profile->profile_image}}" alt="user image">
            <span class="username">
              <a>Edit Your Post</a>
            </span>
            <span class="description">Shared publicly - {{$data_post->created_at}}</span>
          </div>
          <div class="box-tools">
            <a href="/home" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></a>
          </div>
        </div>
        <!-- /.box-header -->
        <form action="{{ route('post.update', $data_post->id) }}" method="POST">
          {{csrf_field()}}
          @method('put')
          <div class="box-body p-2">
            <img class="img-responsive center-block" src="{{URL::to('/')}}/postImage/{{$data_post->post_image}}" alt="Photo">
            <br>
            <div class="form-group mr-3 ml-3">
              <textarea class="form-control" id="post_content" name="post_content" rows="3" placeholder="White something .... " required>{{$data_post->post_content}}</textarea>
            </div>
            <div class="row mr-2 ml-2 mb-2">
              <div class="col-md-12">
                <button class="btn btn-primary btn-sm pull-right pr-3" type="submit"><i class="fa fa-save"></i> Update</button>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </form>
      </div>
      <!-- /.Edit Post -->
    </div>
  </div>
</section>
@endsection

resources/views/post/index.blade.php
@extends('layouts.master')
@section('content')
<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <!-- Create Post -->
        <div class="box">
          <div class="box-header border-transparent">
            <div class="user-block">
              <img class="img-circle img-bordered-sm" src="{{URL::to('/')}}/profileImage/{{Auth::user()->profile->profile_image}}" alt="user image">
              <span class="username">
                <a>Create Your Post</a>
              </span>
              <span class="description">Post as - {{ Auth::user()->name }}</span>
            </div>
          </div>
          <!-- /.box-header -->
          <form action="{{route('post.store')}}" method="POST" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="box-body p-0">
              <div class="form-group mr-3 ml-3">
                <textarea class="form-control" id="post_content" name="post_content" rows="3" placeholder="White something .... " required>{{old('post_content')}}</textarea>
              </div>
              <div class="row mr-2 ml-2 mb-2">
                <div class="col-md-8">
                  <div class="custom-file custom-file-sm">
                    <input type="file" class="custom-file-input-sm" id="postImageName" name="postImageName" aria-describedby="inputGroupFileAddon04" required>
                  </div>
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-sm pull-right" type="submit"><i class="fa fa-paper-plane"></i> Post</button>
                </div>
              </div>
            </div>
            <!-- /.card-body -->
          </form>
        </div>
        <!-- /.Create Post -->

        <!-- Posted -->
        @foreach($data_post as $post)
        <div class="box">
          <div class="box-header">
            <div class="user-block">
              <img class="img-circle img-bordered-sm" src="{{URL::to('/')}}/profileImage/{{$post->user->profile->profile_image}}" alt="user image">
              <span class="username">
                @if ($post->user_id == Auth::user()->id)
                <a href="{{route('profile.index')}}">{{$post->user->name}}</a>
                @else
                <a href="{{route('profile.show',$post->user->id)}}">{{$post->user->name}}</a>
                @endif
              </span>
              <span class="description">Shared publicly - {{$post->created_at->diffForHumans()}}</span>
            </div>
            @if ($post->user_id == Auth::user()->id)
            <div class="box-tools">
              <button type="button" class="btn btn-tool">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{{route('post.edit', $post->id)}}"><i class="fa fa-edit"></i>Edit This Post</a></li>
                  <li>
                    <a href="{{ route('post.destroy', $post->id) }}" onclick="event.preventDefault();
                      document.getElementById('delete').submit();">
                      <i class="fa fa-trash"></i>{{ __('Remove This Post')}}
                    </a>
                    <form id="delete" action="{{ route('post.destroy', $post->id) }}" method="POST" style="display: none;">
                      @csrf
                      @method('delete')
                    </form>
                  </li>
                </ul>
              </button>
            </div>
            @endif
          </div>
          <!-- /.user-block -->
          <div class="box-body">
            <div class="post">
              <img class="img-responsive" src="{{URL::to('/')}}/postImage/{{$post->post_image}}" alt="Photo">
              <p>
                {{$post->post_content}}
              </p>
              <ul class="list-inline">
                <li><a href="{{route('post.like', ['id'=>$post->id])}}" class="link-black text-sm"><i class="fa fa-thumbs-up"></i> Like ({{DB::table('like_posts')->where('post_id', $post->id)->count()}})</a></li>
                <li><a href="{{route('post.show',$post->id)}}" class="link-black text-sm"><i class="fa fa-comment"></i> Comment ({{DB::table('comment_posts')->where('post_id', $post->id)->count()}})</a></li>
              </ul>
            </div>
          </div>
          <div class="box-footer">
            <form action="{{ route('post.comment.store', $post) }}" method="post">
              {{csrf_field()}}
              <img class="img-responsive img-circle img-sm" src="{{URL::to('/')}}/profileImage/{{Auth::user()->profile->profile_image}}" alt="Alt Text">
              <!-- .img-push is used to add margin to elements next to floating images -->
              <div class="img-push">
                <div class="input-group">
                  <input type="text" name="commenntPost_content" id="commenntPost_content" placeholder="Type comment ..." class="form-control" required>
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-success btn-flat">Send</button>
                  </span>
                </div>
              </div>
            </form>
          </div>
        </div>
        @endforeach
        <!-- /Posted -->
      </div>

      <!-- Right Colom  -->
      <div class="col-md-3">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Latest Post</h3>

            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
              </button>
              <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <ul class="products-list product-list-in-box">
              @foreach($latest_post as $lPost)
              <li class="item">
                <div class="product-img">
                  <img src="{{URL::to('/')}}/postImage/{{$lPost->post_image}}" alt="Image">
                </div>
                <div class="product-info">
                  <a href="{{route('post.show',$lPost->id)}}" class="product-title">{{$lPost->user->name}}
                    <span class="label label-success pull-right">{{$lPost->created_at->diffForHumans()}}</span></a>
                  <span class="product-description">
                    {{$lPost->post_content}}
                  </span>
                </div>
              </li>
              @endforeach
            </ul>
          </div>
          <!-- /.box-body -->
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/post/show.blade.php
@extends('layouts.master')
@section('content')
<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <!-- Posted -->
        <div class="box">
          <div class="box-header">
            <div class="user-block">
              <img class="img-circle img-bordered-sm" src="{{URL::to('/')}}/profileImage/{{$data_post->user->profile->profile_image}}" alt="user image">
              <span class="username">
                <a href="#">{{$data_post->user->name}}</a>
              </span>
              <span class="description">Shared publicly - {{$data_post->created_at->diffForHumans()}}</span>
            </div>
            @if ($data_post->user_id == Auth::user()->id)
            <div class="box-tools">
              <button type="button" class="btn btn-tool">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{{route('post.edit', $data_post->id)}}"><i class="fa fa-edit"></i>Edit This Post</a></li>
                  <li>
                    <a href="{{ route('post.destroy', $data_post->id) }}" onclick="event.preventDefault();
                      document.getElementById('delete').submit();">
                      <i class="fa fa-trash"></i>{{ __('Remove This Post')}}
                    </a>
                    <form id="delete" action="{{ route('post.destroy', $data_post->id) }}" method="POST" style="display: none;">
                      @csrf
                      @method('delete')
                    </form>
                  </li>
                </ul>
              </button>
            </div>
            @endif
          </div>
          <!-- /.user-block -->
          <div class="box-body">
            <div class="post">
              <img class="img-responsive center-block" src="{{URL::to('/')}}/postImage/{{$data_post->post_image}}" alt="Photo">
              <p>
                {{$data_post->post_content}}
              </p>
              <ul class="list-inline">
                <li><a href="{{route('post.like', ['id'=>$data_post->id])}}" class="link-black text-sm"><i class="fa fa-thumbs-up"></i> Like ({{DB::table('like_posts')->where('post_id', $data_post->id)->count()}})</a></li>
                <li><a href="{{route('post.show',$data_post->id)}}" class="link-black text-sm"><i class="fa fa-comment"></i> Comment ({{DB::table('comment_posts')->where('post_id', $data_post->id)->count()}})</a></li>
              </ul>
            </div>
          </div>
          <div class="box-footer">
            <form action="{{ route('post.comment.store', $data_post) }}" method="post">
              {{csrf_field()}}
              <img class="img-responsive img-circle img-sm" src="{{URL::to('/')}}/profileImage/{{Auth::user()->profile->profile_image}}" alt="Alt Text">
              <!-- .img-push is used to add margin to elements next to floating images -->
              <div class="img-push">
                <div class="input-group">
                  <input type="text" name="commenntPost_content" id="commenntPost_content" placeholder="Type comment ..." class="form-control" required>
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-success btn-flat">Send</button>
                  </span>
                </div>
              </div>
            </form>
          </div>
          <div class="box-footer box-comments">
            @foreach($data_post->commentPost()->orderByRaw('created_at DESC')->get() as $comment)
            <div class="box-comment">
              <!-- User image -->
              <img class="img-circle img-sm" src="{{URL::to('/')}}/profileImage/{{$comment->user->profile->profile_image}}" alt="User Image">
              <div class="comment-text">
                <span class="username">
                  {{$comment->user->name}}
                  <span class="text-muted pull-right">{{$comment->created_at->diffForHumans()}}</span>
                </span><!-- /.username -->
                {{$comment->commentPost_content}}
                <ul class="list-inline">
                  <li><a href="{{route('comment.like', ['id'=>$comment->id])}}" class="link-black text-sm"><i class="fa fa-thumbs-up"></i> Like ({{DB::table('like_comment_posts')->where('commentPost_id', $comment->id)->count()}})</a></li>
                </ul>
              </div>
              <!-- /.comment-text -->
            </div>
            @endforeach
            <!-- /.box-comment -->
          </div>
          <!-- /.box-footer -->
        </div>
        <!-- /Posted -->
      </div>

      <!-- Right Colom  -->
      <div class="col-md-3">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Latest Post</h3>

            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
              </button>
              <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <ul class="products-list product-list-in-box">
              @foreach($latest_post as $lPost)
              <li class="item">
                <div class="product-img">
                  <img src="{{URL::to('/')}}/postImage/{{$lPost->post_image}}" alt="Image">
                </div>
                <div class="product-info">
                  <a href="{{route('post.show',$lPost->id)}}" class="product-title">{{$lPost->user->name}}
                    <span class="label label-success pull-right">{{$lPost->created_at->diffForHumans()}}</span></a>
                  <span class="product-description">
                    {{$lPost->post_content}}
                  </span>
                </div>
              </li>
              @endforeach
            </ul>
          </div>
          <!-- /.box-body -->
        </div>
      </div>
    </div>
  </div>
</section>
@endsection